query AllProjects($first: IntType = 100, $skip: IntType = 0) {
	allProjects(first: $first, skip: $skip, orderBy: position_ASC) {
		...ProjectFragment
	}
	_allProjectsMeta {
		count
	}
}

fragment ProjectFragment on ProjectRecord {
	id
	title
	year
	description {
		blocks
		links
		value
	}
	position
	visualPresentation {
		__typename
		id
		media {
			__typename
			...MediaFragment
		}
	}
	collaborationWith
	externalLink
	slug
}
